export default [
  {
    _id: 1,
    imageUrl: "/assets/images/chatbot.jpeg",
    imageUrl1: "/assets/images/AI Powered Process Discovery.jpg",
    imageUrl2: "/assets/images/AI Powered DIGITAL ASSISTANT.png",
    title: "Digital Assistant",
    description1:
      "Digital Assistant are software applications that use artificial intelligence & natural language processing to understand what a human wants, and guides them to their desired outcome with as little work for the end user as possible.",
    description:
      "Digital Assistant are software applications that use artificial intelligence and natural language processing to understand what a human wants and guides them to their desired outcome. Chatbot applications streamline interactions between people and services, enhancing customer experience.",
    intro: "",
    working: "",
    featured: true,
  },
  {
    _id: 2,
    imageUrl: "/assets/images/smartmask.jpeg",
    title: "Smart Mask Detection",
    description1:
      "Face mask detection feature uses visible stream from the camera combined with AI techniques to detect and generate an alert for people not wearing face masks.",
    description:
      "Face mask detection feature uses visible stream from the camera combined with AI techniques to detect and generate an alert for people not wearing face masks. A user-friendly interface allows monitoring and review of alerts generated by the system.",
    intro:
      "By combining IoT and deep learning, we have built a tangible device that can be placed on the main gate of any public place in the same way as a security camera. There are a few systems already available in the market but they all just provide a standard system. We at EnR provide you your custom system, so you will pay for only what you need.",
    working:
      "It uses a camera that captures the image of the visitor and then our device makes a decision using Artificial intelligence that determines whether the person is wearing a face mask or not and accordingly decides if the person is allowed to enter or not. The device has in-built LEDs and speakers for the output. If the person is wearing a mask then the Green LED flashes and the device says “ACCESS GRANTED”. And if the person is not wearing a mask then Red LED flashes and the device says “ACCESS DENIED”.",
    featured: false,
  },
  {
    _id: 3,
    imageUrl: "/assets/images/hostelmanagement.jpeg",
    title: "Hostel Management Solution",
    description:
      "Our hostel management solution is super-efficient and can store data of thousands of hostlers without any issue. It’s one of the fit for purpose solution that will facilitate to manage students data in an effective way.",
    intro:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices neque ornare aenean euismod elementum. Luctus accumsan tortor posuere ac. Cursus risus at ultrices mi tempus. Adipiscing elit duis tristique sollicitudin nibh sit. Vestibulum mattis ullamcorper velit sed ullamcorper. Libero nunc consequat interdum varius. Habitasse platea dictumst vestibulum rhoncus. At lectus urna duis convallis convallis. Nunc sed velit dignissim sodales. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Morbi tristique senectus et netus et. Nunc non blandit massa enim nec dui. Aenean et tortor at risus viverra adipiscing. At risus viverra adipiscing at in tellus integer feugiat. Vitae ultricies leo integer malesuada nunc. Sed pulvinar proin gravida hendrerit.",
    working:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices neque ornare aenean euismod elementum. Luctus accumsan tortor posuere ac. Cursus risus at ultrices mi tempus. Adipiscing elit duis tristique sollicitudin nibh sit. Vestibulum mattis ullamcorper velit sed ullamcorper. Libero nunc consequat interdum varius. Habitasse platea dictumst vestibulum rhoncus. At lectus urna duis convallis convallis. Nunc sed velit dignissim sodales. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Morbi tristique senectus et netus et. Nunc non blandit massa enim nec dui. Aenean et tortor at risus viverra adipiscing. At risus viverra adipiscing at in tellus integer feugiat. Vitae ultricies leo integer malesuada nunc. Sed pulvinar proin gravida hendrerit.",
    featured: false,
  },
  {
    _id: 4,
    imageUrl: "/assets/images/smartparking1.jpeg",
    title: "EnR Smart Parking",
    description:
      "Smart Parking system is a complete, end-to-end solution that uses latest technology, feature displays and live gateways with a powerful and intuitive web-based platform. This solution primarily uses Automatic Number Plate Recognition (ANPR) systems in their car parks. This solution detects entries and exits into a car park automatically & facilitates user to make payment automatically.",
    intro:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices neque ornare aenean euismod elementum. Luctus accumsan tortor posuere ac. Cursus risus at ultrices mi tempus. Adipiscing elit duis tristique sollicitudin nibh sit. Vestibulum mattis ullamcorper velit sed ullamcorper. Libero nunc consequat interdum varius. Habitasse platea dictumst vestibulum rhoncus. At lectus urna duis convallis convallis. Nunc sed velit dignissim sodales. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Morbi tristique senectus et netus et. Nunc non blandit massa enim nec dui. Aenean et tortor at risus viverra adipiscing. At risus viverra adipiscing at in tellus integer feugiat. Vitae ultricies leo integer malesuada nunc. Sed pulvinar proin gravida hendrerit.",
    working:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices neque ornare aenean euismod elementum. Luctus accumsan tortor posuere ac. Cursus risus at ultrices mi tempus. Adipiscing elit duis tristique sollicitudin nibh sit. Vestibulum mattis ullamcorper velit sed ullamcorper. Libero nunc consequat interdum varius. Habitasse platea dictumst vestibulum rhoncus. At lectus urna duis convallis convallis. Nunc sed velit dignissim sodales. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Morbi tristique senectus et netus et. Nunc non blandit massa enim nec dui. Aenean et tortor at risus viverra adipiscing. At risus viverra adipiscing at in tellus integer feugiat. Vitae ultricies leo integer malesuada nunc. Sed pulvinar proin gravida hendrerit.",
    featured: false,
  },
  {
    _id: 5,
    imageUrl: "/assets/images/smartrefrigerator.jpeg",
    title: "EnR Smart Refrigerator",
    description:
      "EnR brings a smart device for your refrigeration, that is capable of detecting the quality and measuring the quantity of food products stored inside it.This product brings a Next Generation Smart Refrigeration enriched with sensors, camera and image recognition mechanism.",
    intro:
      "To create a system that can detect fruits and vegetables inside a fridge, and also get the count of each of them. These predictions can be then sent to a mobile app that can be displayed to the user.",
    working:
      "A total of 13 classes have been included in the current model. The number of classes can be increased by sending the weights files to the hardware after training the model on more number of classes. The list of fruits and vegetables included are: Apple, Banana, Cabbage, Carrot, Grape, Mango, Orange, Pineapple, Pomegranate, Potato, Tomato, Watermelon and Strawberry",
    featured: false,
  },

  {
    _id: 6,
    imageUrl: "/assets/images/employeemanagement.jpeg",
    title: "Employee Management Portal",
    describe: "",
    description:
      "Employee management is a process that helps your workers perform at their best and achieve your business goals. It’s a holistic process that covers almost everything related to human resources such as new employee recruitment, payroll management, performance management and more.",
    intro:
      "This is a software through which all the details of all the individuals working on the company is kept digital and safe and it can be easily access by the authorize person in the company. Through this, we can achieve more productivity in the company.",
    working:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices neque ornare aenean euismod elementum. Luctus accumsan tortor posuere ac. Cursus risus at ultrices mi tempus. Adipiscing elit duis tristique sollicitudin nibh sit. Vestibulum mattis ullamcorper velit sed ullamcorper. Libero nunc consequat interdum varius. Habitasse platea dictumst vestibulum rhoncus. At lectus urna duis convallis convallis. Nunc sed velit dignissim sodales. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Morbi tristique senectus et netus et. Nunc non blandit massa enim nec dui. Aenean et tortor at risus viverra adipiscing. At risus viverra adipiscing at in tellus integer feugiat. Vitae ultricies leo integer malesuada nunc. Sed pulvinar proin gravida hendrerit.",
    featured: false,
  },
  {
    _id: 7,
    imageUrl: "/assets/images/examportal.jpeg",
    title: "Online Examination Portal",
    description:
      "An online examination system is a computer-based test system that can be used to conduct computer based tests online. This examination system uses fewer resources and reduces the need for question papers and answer scripts, exam room scheduling, arranging invigilators, coordinating with examiners, and more. ",
    intro:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices neque ornare aenean euismod elementum. Luctus accumsan tortor posuere ac. Cursus risus at ultrices mi tempus. Adipiscing elit duis tristique sollicitudin nibh sit. Vestibulum mattis ullamcorper velit sed ullamcorper. Libero nunc consequat interdum varius. Habitasse platea dictumst vestibulum rhoncus. At lectus urna duis convallis convallis. Nunc sed velit dignissim sodales. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Morbi tristique senectus et netus et. Nunc non blandit massa enim nec dui. Aenean et tortor at risus viverra adipiscing. At risus viverra adipiscing at in tellus integer feugiat. Vitae ultricies leo integer malesuada nunc. Sed pulvinar proin gravida hendrerit.",
    working:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices neque ornare aenean euismod elementum. Luctus accumsan tortor posuere ac. Cursus risus at ultrices mi tempus. Adipiscing elit duis tristique sollicitudin nibh sit. Vestibulum mattis ullamcorper velit sed ullamcorper. Libero nunc consequat interdum varius. Habitasse platea dictumst vestibulum rhoncus. At lectus urna duis convallis convallis. Nunc sed velit dignissim sodales. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Morbi tristique senectus et netus et. Nunc non blandit massa enim nec dui. Aenean et tortor at risus viverra adipiscing. At risus viverra adipiscing at in tellus integer feugiat. Vitae ultricies leo integer malesuada nunc. Sed pulvinar proin gravida hendrerit.",
    featured: false,
  },
  {
    _id: 8,
    imageUrl: "/assets/images/facialrecog.jpeg",
    title: "Facial Recognition System",
    description:
      "A facial recognition system is a technology capable of matching a human face from a digital image or a video frame against a database of faces, typically employed to authenticate users through ID verification services, works by pinpointing and measuring facial features from a given image.",
    intro:
      "A model trained to detect faces of students in a photo and mark their attendance in database",
    working:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices neque ornare aenean euismod elementum. Luctus accumsan tortor posuere ac. Cursus risus at ultrices mi tempus. Adipiscing elit duis tristique sollicitudin nibh sit. Vestibulum mattis ullamcorper velit sed ullamcorper. Libero nunc consequat interdum varius. Habitasse platea dictumst vestibulum rhoncus. At lectus urna duis convallis convallis. Nunc sed velit dignissim sodales. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Morbi tristique senectus et netus et. Nunc non blandit massa enim nec dui. Aenean et tortor at risus viverra adipiscing. At risus viverra adipiscing at in tellus integer feugiat. Vitae ultricies leo integer malesuada nunc. Sed pulvinar proin gravida hendrerit.",
    featured: false,
  },
  {
    _id: 9,
    imageUrl: "/assets/images/onlinegroceries.jpeg",
    title: "EnR Online Groceries",
    description:
      "Our EnR Online Groceries provides a digital platform for retailers to sell groceries, fruits, vegetables, and all essentials. We offer an affordable economic price to setup your online shop and manage it efficiently.The whole sector moved online. Gone are the days when we used to stand in long lines for our groceries; now getting our groceries is just a matter of few clicks.",
    intro:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices neque ornare aenean euismod elementum. Luctus accumsan tortor posuere ac. Cursus risus at ultrices mi tempus. Adipiscing elit duis tristique sollicitudin nibh sit. Vestibulum mattis ullamcorper velit sed ullamcorper. Libero nunc consequat interdum varius. Habitasse platea dictumst vestibulum rhoncus. At lectus urna duis convallis convallis. Nunc sed velit dignissim sodales. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Morbi tristique senectus et netus et. Nunc non blandit massa enim nec dui. Aenean et tortor at risus viverra adipiscing. At risus viverra adipiscing at in tellus integer feugiat. Vitae ultricies leo integer malesuada nunc. Sed pulvinar proin gravida hendrerit.",
    working:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices neque ornare aenean euismod elementum. Luctus accumsan tortor posuere ac. Cursus risus at ultrices mi tempus. Adipiscing elit duis tristique sollicitudin nibh sit. Vestibulum mattis ullamcorper velit sed ullamcorper. Libero nunc consequat interdum varius. Habitasse platea dictumst vestibulum rhoncus. At lectus urna duis convallis convallis. Nunc sed velit dignissim sodales. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Morbi tristique senectus et netus et. Nunc non blandit massa enim nec dui. Aenean et tortor at risus viverra adipiscing. At risus viverra adipiscing at in tellus integer feugiat. Vitae ultricies leo integer malesuada nunc. Sed pulvinar proin gravida hendrerit.",
    featured: false,
  },
];
